cards = [
    {'name': 'A', 'type': 'Hearts'},
    {'name': 'A', 'type': 'Diamonds'},
    {'name': 'A', 'type': 'Spades'},
    {'name': 'A', 'type': 'Flowers'},
    {'name': '2', 'type': 'Hearts'},
    {'name': '2', 'type': 'Diamonds'},
    {'name': '2', 'type': 'Spades'},
    {'name': '2', 'type': 'Flowers'},
    {'name': '3', 'type': 'Hearts'},
    {'name': '3', 'type': 'Diamonds'},
    {'name': '3', 'type': 'Spades'},
    {'name': '3', 'type': 'Flowers'},
    {'name': '4', 'type': 'Hearts'},
    {'name': '4', 'type': 'Diamonds'},
    {'name': '4', 'type': 'Spades'},
    {'name': '4', 'type': 'Flowers'},
    {'name': '5', 'type': 'Hearts'},
    {'name': '5', 'type': 'Diamonds'},
    {'name': '5', 'type': 'Spades'},
    {'name': '5', 'type': 'Flowers'},
    {'name': '6', 'type': 'Hearts'},
    {'name': '6', 'type': 'Diamonds'},
    {'name': '6', 'type': 'Spades'},
    {'name': '6', 'type': 'Flowers'},
    {'name': '7', 'type': 'Hearts'},
    {'name': '7', 'type': 'Diamonds'},
    {'name': '7', 'type': 'Spades'},
    {'name': '7', 'type': 'Flowers'},
    {'name': '8', 'type': 'Hearts'},
    {'name': '8', 'type': 'Diamonds'},
    {'name': '8', 'type': 'Spades'},
    {'name': '8', 'type': 'Flowers'},
    {'name': '9', 'type': 'Hearts'},
    {'name': '9', 'type': 'Diamonds'},
    {'name': '9', 'type': 'Spades'},
    {'name': '9', 'type': 'Flowers'},
    {'name': '10', 'type': 'Hearts'},
    {'name': '10', 'type': 'Diamonds'},
    {'name': '10', 'type': 'Spades'},
    {'name': '10', 'type': 'Flowers'},
    {'name': 'K', 'type': 'Hearts'},
    {'name': 'K', 'type': 'Diamonds'},
    {'name': 'K', 'type': 'Spades'},
    {'name': 'K', 'type': 'Flowers'},
    {'name': 'Q', 'type': 'Hearts'},
    {'name': 'Q', 'type': 'Diamonds'},
    {'name': 'Q', 'type': 'Spades'},
    {'name': 'Q', 'type': 'Flowers'},
    {'name': 'J', 'type': 'Hearts'},
    {'name': 'J', 'type': 'Diamonds'},
    {'name': 'J', 'type': 'Spades'},
    {'name': 'J', 'type': 'Flowers'},
]

Letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
           'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

Numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
